### ISSUE TITLE
ReferenceError: loadScript is not defined

### ISSUE THREAD

**Issue by IlyaSemenov** [deshiknaves/async-script-loader#1]
The examples are clearly invalid. You import one thing and call another, which results in `ReferenceError: loadScript is not defined`

**Comment by deshiknaves** [comment]
Yep, you’re absolutely right. I called them loadscript when I was working with it, but added the import line after. I’ll update it in a bit. But it’s pretty obvious that you would use the function that was just imported.

________________________________

**Comment by deshiknaves** [comment]
Documentation has been updated.
